insert into Bank(id, name, code, url) values (1, 'Bank 1', '111111', 'http://localhost/bank1');
insert into Bank(id, name, code, url) values (2, 'Bank 2', '222222', 'http://localhost/bank2');
insert into Bank(id, name, code, url) values (3, 'Bank 3', '333333', 'http://localhost/bank3');
insert into Bank(id, name, code, url) values (4, 'Bank 4', '444444', 'http://localhost/bank4');
insert into Bank(id, name, code, url) values (5, 'Bank 5', '555555', 'http://localhost/bank5');
insert into Bank(id, name, code, url) values (6, 'Bank 6', '666666', 'http://localhost/bank6');
insert into Bank(id, name, code, url) values (7, 'Bank 7', '777777', 'http://localhost/bank7');
insert into Bank(id, name, code, url) values (8, 'Bank 8', '888888', 'http://localhost/bank8');
insert into Bank(id, name, code, url) values (9, 'Bank 9', '999999', 'http://localhost/bank9');
